CMAKE_MINIMUM_REQUIRED(VERSION 2.8)

SET(WD ${CMAKE_CURRENT_LIST_DIR}/)
SET(SERVER_EXECUTABLE_TARGET server_executable)

ADD_EXECUTABLE(${SERVER_EXECUTABLE_TARGET} ${WD}main.cpp)

TARGET_LINK_LIBRARIES(${SERVER_EXECUTABLE_TARGET} server/server)

SET(OUTPUT_DIR ${WD}../../game/bin)

SET_TARGET_PROPERTIES(${SERVER_EXECUTABLE_TARGET}
	PROPERTIES
	RUNTIME_OUTPUT_DIRECTORY_DEBUG   "${OUTPUT_DIR}"
	RUNTIME_OUTPUT_DIRECTORY_RELEASE "${OUTPUT_DIR}"
)

ADD_DEPENDENCIES(${SERVER_EXECUTABLE_TARGET} ${SHARED_TARGET} ${SERVER_TARGET})

CONFIGURE_FILE(CMakeVCDebuggingTemplate.txt ${CMAKE_CURRENT_BINARY_DIR}/${SERVER_EXECUTABLE_TARGET}.vcxproj.user @ONLY)