CMAKE_MINIMUM_REQUIRED(VERSION 2.8)

SET(WD ${CMAKE_CURRENT_LIST_DIR}/)
SET(CLIENT_TARGET client)

SET(${CLIENT_TARGET}_SOURCE_FILES
	${WD}Client.cpp
	${WD}ClientUpdateManager.cpp
	${WD}WorldRenderer.cpp
)

SET(${CLIENT_TARGET}_HEADER_FILES
	${WD}Client.h
	${WD}ClientPhysicsEntity.h
	${WD}ClientPlayerEntity.h
	${WD}ClientUpdateManager.h
	${WD}ClientFactoryManifest.h
	${WD}InputManager.h
	${WD}WorldRenderer.h
)

ADD_LIBRARY(${CLIENT_TARGET} SHARED ${${CLIENT_TARGET}_SOURCE_FILES})

TARGET_LINK_LIBRARIES(${CLIENT_TARGET} kernel32)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} user32)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} gdi32)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} winspool)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} shell32)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} ole32)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} oleaut32)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} uuid)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} comdlg32)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} advapi32)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} opengl32)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} glu32)

TARGET_LINK_LIBRARIES(${CLIENT_TARGET} zlib/zlib)

TARGET_LINK_LIBRARIES(${CLIENT_TARGET} shared/shared)

TARGET_LINK_LIBRARIES(${CLIENT_TARGET} optimized sfml/sfml-system-s)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} debug     sfml/sfml-system-s-d)

TARGET_LINK_LIBRARIES(${CLIENT_TARGET} optimized sfml/sfml-window-s)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} debug     sfml/sfml-window-s-d)

TARGET_LINK_LIBRARIES(${CLIENT_TARGET} optimized sfml/sfml-network-s)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} debug     sfml/sfml-network-s-d)

TARGET_LINK_LIBRARIES(${CLIENT_TARGET} optimized sfml/sfml-graphics-s)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} debug     sfml/sfml-graphics-s-d)

TARGET_LINK_LIBRARIES(${CLIENT_TARGET} optimized sfml/sfml-audio-s)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} debug     sfml/sfml-audio-s-d)

TARGET_LINK_LIBRARIES(${CLIENT_TARGET} optimized jsoncpp/jsoncpp)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} debug     jsoncpp/jsoncpp-d)

TARGET_LINK_LIBRARIES(${CLIENT_TARGET} optimized stlplus/portability)
TARGET_LINK_LIBRARIES(${CLIENT_TARGET} debug     stlplus/portability-d)

SET_TARGET_PROPERTIES(${CLIENT_TARGET}
	PROPERTIES
	COMPILE_FLAGS "/FIshared/Debug.h"
	COMPILE_DEFINITIONS SFML_STATIC
	
	ARCHIVE_OUTPUT_DIRECTORY_DEBUG   "${WD}../../public/importlibs/client"
	ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${WD}../../public/importlibs/client"
	
	RUNTIME_OUTPUT_DIRECTORY_DEBUG   "${WD}../../../game/bin"
	RUNTIME_OUTPUT_DIRECTORY_RELEASE "${WD}../../../game/bin"
)

ADD_DEPENDENCIES(${CLIENT_TARGET} ${SHARED_TARGET})